name: Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action

  roave-bc-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga

  phpcsfixer-check:
    name: PHP-CS-Fixer Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer Check
        uses: docker://oskarstark/php-cs-fixer-ga
          with:
            args: --config=.project.php_cs --diff --dry-run
